services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: autorent
      POSTGRES_USER: auto_user
      POSTGRES_PASSWORD: auto_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: